// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fastFantopeProjCpp
arma::mat fastFantopeProjCpp(arma::mat& S, int& ndim);
RcppExport SEXP fastFPS_fastFantopeProjCpp(SEXP SSEXP, SEXP ndimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< int& >::type ndim(ndimSEXP);
    __result = Rcpp::wrap(fastFantopeProjCpp(S, ndim));
    return __result;
END_RCPP
}
// tryEigs
arma::sp_mat tryEigs(arma::sp_mat S, int ndim);
RcppExport SEXP fastFPS_tryEigs(SEXP SSEXP, SEXP ndimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::sp_mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type ndim(ndimSEXP);
    __result = Rcpp::wrap(tryEigs(S, ndim));
    return __result;
END_RCPP
}
// sparse
arma::sp_mat sparse(arma::sp_mat A);
RcppExport SEXP fastFPS_sparse(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::sp_mat >::type A(ASEXP);
    __result = Rcpp::wrap(sparse(A));
    return __result;
END_RCPP
}
// softThresholdCpp
arma::mat softThresholdCpp(arma::mat& x, double& lambda);
RcppExport SEXP fastFPS_softThresholdCpp(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double& >::type lambda(lambdaSEXP);
    __result = Rcpp::wrap(softThresholdCpp(x, lambda));
    return __result;
END_RCPP
}
