// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// softThresholdCpp
arma::mat softThresholdCpp(arma::mat& x, double& lambda);
RcppExport SEXP fastFPS_softThresholdCpp(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double& >::type lambda(lambdaSEXP);
    __result = Rcpp::wrap(softThresholdCpp(x, lambda));
    return __result;
END_RCPP
}
// timesTwo
int timesTwo(int x);
RcppExport SEXP fastFPS_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    __result = Rcpp::wrap(timesTwo(x));
    return __result;
END_RCPP
}
