# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastFantopeProjCpp <- function(S, ndim) {
    .Call('fastFPS_fastFantopeProjCpp', PACKAGE = 'fastFPS', S, ndim)
}

softThresholdCpp <- function(x, lambda) {
    .Call('fastFPS_softThresholdCpp', PACKAGE = 'fastFPS', x, lambda)
}

