# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

softThresholdCpp <- function(x, lambda) {
    .Call('fastFPS_softThresholdCpp', PACKAGE = 'fastFPS', x, lambda)
}

timesTwo <- function(x) {
    .Call('fastFPS_timesTwo', PACKAGE = 'fastFPS', x)
}

